FROM resin/raspberrypi3-debian:jessie

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
      python3 \
      python3-flask \
      python3-requests \
      sense-hat \
      raspberrypi-bootloader \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . ./

CMD ["bash", "start.sh"]
